name: Build Anchor BPF

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install Solana CLI & BPF SDK
        run: |
          curl -sSfL https://release.solana.com/v1.18.26/install/solana-install-init.sh \
            | sh -s v1.18.26
          source ~/.profile

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Anchor CLI via npm
        run: npm install -g @coral-xyz/anchor-cli@0.31.1

      - name: Build Anchor program
        run: anchor build

      - name: Upload BPF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ikiru-so
          path: target/deploy/*.so
